# Generated by Django 3.1 on 2020-09-16 06:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(10)])),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('single', 'single'), ('married', 'married')], default='single', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=20)),
                ('phone_no', models.CharField(blank=True, default='0300-0000000', max_length=15, null=True, validators=[django.core.validators.RegexValidator('[0]{1}[3]{1}[0-9]{2}[-]{1}[0-9]{7}')])),
                ('description', models.TextField(blank=True, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='gym/images/')),
                ('time', models.IntegerField(blank='True', default=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('[0]{1}[3]{1}[0-9]{2}[-]{1}[0-9]{7}$')])),
                ('subject', models.CharField(max_length=30)),
                ('msg', models.TextField()),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=20)),
                ('chest', models.CharField(blank=True, max_length=100, null=True)),
                ('back', models.CharField(blank=True, max_length=100, null=True)),
                ('shoulder', models.CharField(blank=True, max_length=100, null=True)),
                ('bitri', models.CharField(blank=True, max_length=100, null=True)),
                ('leg', models.CharField(blank=True, max_length=100, null=True)),
                ('six_pack', models.CharField(blank=True, max_length=100, null=True)),
                ('cardio', models.CharField(blank=True, max_length=100, null=True)),
                ('weight_lose', models.CharField(blank=True, max_length=100, null=True)),
                ('balley_lose', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
